import type { Transaction } from "@/lib/types";

export const mockData: Transaction[] = [
  {
    id: "txn_001",
    date: "2024-05-01",
    amount: 1200,
    product: "لابتوب حديث",
    category: "إلكترونيات",
    paymentMethod: "بطاقة ائتمان",
  },
  {
    id: "txn_002",
    date: "2024-05-01",
    amount: 150,
    product: "قميص قطني",
    category: "ملابس",
    paymentMethod: "نقد",
  },
  {
    id: "txn_003",
    date: "2024-05-02",
    amount: 50,
    product: "وجبة غداء",
    category: "طعام",
    paymentMethod: "بطاقة ائتمان",
  },
  {
    id: "txn_004",
    date: "2024-05-03",
    amount: 800,
    product: "كرسي مكتب",
    category: "أثاث",
    paymentMethod: "تحويل بنكي",
  },
  {
    id: "txn_005",
    date: "2024-05-04",
    amount: 75,
    product: "رواية جديدة",
    category: "كتب",
    paymentMethod: "نقد",
  },
  {
    id: "txn_006",
    date: "2024-05-05",
    amount: 2500,
    product: "شاشة 4K",
    category: "إلكترونيات",
    paymentMethod: "بطاقة ائتمان",
  },
    {
    id: "txn_007",
    date: "2024-05-06",
    amount: 300,
    product: "حذاء رياضي",
    category: "ملابس",
    paymentMethod: "بطاقة ائتمان",
  },
  {
    id: "txn_008",
    date: "2024-05-07",
    amount: 25,
    product: "قهوة ومخبوزات",
    category: "طعام",
    paymentMethod: "نقد",
  },
    {
    id: "txn_009",
    date: "2024-05-08",
    amount: 1800,
    product: "هاتف ذكي",
    category: "إلكترونيات",
    paymentMethod: "بطاقة ائتمان",
  },
  {
    id: "txn_010",
    date: "2024-05-09",
    amount: 220,
    product: "معطف شتوي",
    category: "ملابس",
    paymentMethod: "نقد",
  },
];
